Repository IBAD-Ibirama/ibad, pull requests merged in 2020-09, with the labels that each got.

#7 feat: Sponsor
  app/Http/Controllers/MovesController.php
  app/Http/Controllers/SponsorController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Moves.php
  app/Providers/AuthServiceProvider.php
  app/Sponsor.php
  composer.json
  composer.lock
  database/factories/MovesFactory.php
  database/factories/SponsorFactory.php
  database/migrations/2020_08_18_235117_create_moves_table.php
  database/migrations/2020_08_23_003728_create_sponsors_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/MovesSeeder.php
  database/seeds/PermissionsSeeder.php
  database/seeds/SponsorSeeder.php
  resources/views/layouts/app.blade.php
  resources/views/moves/create.blade.php
  resources/views/moves/edit.blade.php
  resources/views/moves/index.blade.php
  resources/views/moves/show.blade.php
  resources/views/sponsors/create.blade.php
  resources/views/sponsors/edit.blade.php
  resources/views/sponsors/index.blade.php
  resources/views/sponsors/show.blade.php
  resources/views/users/create.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/index.blade.php
  resources/views/users/show.blade.php
  routes/web.php
Labels: type: grupo 1

#8 feat: create CRUD for athletes section
  app/Athlete.php
  app/Http/Controllers/AthleteController.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  database/factories/AthleteFactory.php
  database/migrations/2020_09_01_191722_create_athletes_table.php
  database/migrations/2020_09_08_002904_add_user_id_to_athletes_table.php
  database/seeds/AthleteSeeder.php
  package-lock.json
  package.json
  public/images/vendor/lightbox2/dist/close.png
  public/images/vendor/lightbox2/dist/loading.gif
  public/images/vendor/lightbox2/dist/next.png
  public/images/vendor/lightbox2/dist/prev.png
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/sass/_variables.scss
  resources/sass/app.scss
  resources/sass/custom.scss
  resources/views/athletes/create.blade.php
  resources/views/athletes/edit.blade.php
  resources/views/athletes/index.blade.php
  resources/views/athletes/show.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: type: grupo 1

#9 Grupo 1/relatorio movimentacoes
  app/Http/Controllers/MovesController.php
  app/Http/Controllers/MovesReportController.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  resources/views/moves/index.blade.php
  resources/views/pdf.blade.php
  routes/web.php
Labels: type: grupo 1

#15 Geração de recibos - Módulo 1
  app/Http/Controllers/MovesController.php
  app/Http/Controllers/MovesReceiptController.php
  app/Moves.php
  app/User.php
  composer.json
  composer.lock
  database/migrations/2020_09_17_230819_add_user_id_to_moves_table.php
  database/seeds/MovesSeeder.php
  resources/views/moves/create.blade.php
  resources/views/moves/edit.blade.php
  resources/views/moves/index.blade.php
  resources/views/receipt.blade.php
  routes/web.php
Labels: type: grupo 1

#16 feat: cadastro de responsáveis
  app/Athlete.php
  app/Http/Controllers/ResponsibleController.php
  app/Responsible.php
  database/migrations/2020_09_15_225026_create_responsibles_table.php
  database/migrations/2020_09_17_194521_create_responsible_athlete_table.php
  database/migrations/2020_09_17_194633_add_user_id_to_responsibles_table.php
  public/js/pages/responsibles.js
  resources/views/layouts/app.blade.php
  resources/views/responsibles/create.blade.php
  resources/views/responsibles/edit.blade.php
  resources/views/responsibles/index.blade.php
  resources/views/responsibles/show.blade.php
  routes/web.php
Labels: type: grupo 1

#30 test: novos testes e workflow para PR
  .github/workflows/test.yml
  app/Console/Kernel.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/MovesController.php
  app/Http/Controllers/MovesReportController.php
  app/Http/Controllers/SponsorController.php
  app/Http/Controllers/UserController.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  app/User.php
  config/cache.php
  config/database.php
  config/filesystems.php
  config/session.php
  database/factories/AthleteFactory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2014_10_12_100000_create_password_resets_table.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2020_08_09_145707_create_permission_tables.php
  database/migrations/2020_08_18_235117_create_moves_table.php
  database/migrations/2020_08_23_003728_create_sponsors_table.php
  database/migrations/2020_09_01_191722_create_athletes_table.php
  database/migrations/2020_09_08_002904_add_user_id_to_athletes_table.php
  database/seeds/DatabaseSeeder.php
  phpunit.xml
  resources/views/layouts/app.blade.php
  resources/views/moves/index.blade.php
  resources/views/moves/show.blade.php
  resources/views/pdf.blade.php
  resources/views/sponsors/create.blade.php
  resources/views/sponsors/edit.blade.php
  resources/views/sponsors/index.blade.php
  resources/views/sponsors/show.blade.php
  resources/views/users/index.blade.php
  routes/web.php
  seleniumTestsIbad.side
  tests/Builders/MovesBuilder.php
  tests/Builders/SponsorBuilder.php
  tests/Builders/UserBuilder.php
  tests/CreatesApplication.php
  tests/Feature/AthleteTest.php
  tests/Feature/MovesTest.php
  tests/Feature/SponsorTest.php
  tests/Feature/UserTest.php
  tests/TestCase.php
  tests/Unit/.gitkeep
  tests/Unit/ExampleTest.php
Labels: type: grupo 1

#28 feat: cadastro de avaliacoes, graficos de evolucao e plano de treino
  app/Athlete.php
  app/AthleteEvaluation.php
  app/AthleteEvaluationBodyIndex.php
  app/AthleteEvaluationPhysicalTest.php
  app/BodyIndex.php
  app/Charts/AthleteEvaluationBodyIndexChart.php
  app/Charts/AthleteEvaluationPhysicalTestChart.php
  app/Http/Controllers/AthleteEvaluationChartController.php
  app/Http/Controllers/AthleteEvaluationController.php
  app/Http/Controllers/PlanningController.php
  app/Http/Requests/AthleteEvaluationForm.php
  app/Http/Requests/PlanningForm.php
  app/PhysicalTest.php
  app/Planning.php
  app/Training.php
  composer.json
  config/charts.php
  database/migrations/2020_08_18_014617_create_physical_tests_table.php
  database/migrations/2020_08_18_025254_create_body_indexes_table.php
  database/migrations/2020_09_09_234713_create_athlete_evaluations_table.php
  database/migrations/2020_09_10_015839_create_athlete_evaluation_physical_test_table.php
  database/migrations/2020_09_10_230706_create_athlete_evaluation_body_index_table.php
  database/migrations/2020_09_12_001708_create_plannings_table.php
  database/seeds/BodyIndexSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/PhysicalTestSeeder.php
  resources/views/athlete_evaluation/edit.blade.php
  resources/views/athlete_evaluation/index.blade.php
  resources/views/athlete_evaluation/show.blade.php
  resources/views/athlete_evaluation_chart/index.blade.php
  resources/views/athletes/index.blade.php
  resources/views/athletes/show.blade.php
  resources/views/plannings/edit.blade.php
  resources/views/plannings/index.blade.php
  resources/views/plannings/show.blade.php
  resources/views/training/index.blade.php
  routes/web.php
Labels: type: grupo 4

#32 chore: added coach and financial links on a dropdown
  resources/views/layouts/app.blade.php
Labels: type: maintenance
